module.exports = {
	// 父元素选项
	parentData: [
		{ label: '压力',     value: 1 },
		{ label: '气体',     value: 2 },
		{ label: '分钟容量',  value: 3 },
		{ label: '时间/周期', value: 4 },
		{ label: '容量流量',  value: 5 },
		{ label: '其他',     value: 6 },
	],
	// 子元素选项
	childMap: {
		1: [
			{ label: 'PIP',   value: 'PEAK' },
			{ label: 'Pplat', value: 'PPLAT' },
			{ label: 'Pmean', value: 'PMEAN' },
			{ label: 'PEEP',  value: 'PEEP' },
			{ label: '△P',    value: '△P' },
		],
		2: [
			{ label: 'FiO₂',  value: 'FIO2' },
			{ label: 'etCO₂', value: 'ETCO2' },
		],
		3: [
			{ label: 'MVe', value: 'MVE' },
			{ label: 'MVi', value: 'MVI', disabled: true },
		],
		4: [
			{ label: 'Ti',      value: 'TI' },
			{ label: 'I:E',     value: 'IE' },
			{ label: 'TCe',     value: 'TCE' },
			{ label: 'Tplat',   value: 'TPLAT' },
			{ label: 'RR',      value: 'RR' },
			{ label: 'RRspont', value: 'RRSPONT'},
		],
		5: [
			{ label: 'VTe',      value: 'VTE' },
			{ label: 'VTi',      value: 'VTI', disabled: true },
			{ label: 'VT/kg BW', value: 'VTKGBW' },
			{ label: 'PIF',      value: 'PIF' },
			{ label: 'PEF',      value: 'PEF' },
		],
		6: [
			{ label: 'C',   value: 'C' },
			{ label: 'R',   value: 'R' },
			{ label: 'RSB', value: 'RSB', disabled: true },
		],
	},
	// 父元素Id映射
	parentMap: {
		'PEAK':     1,
		'PPLAT':    1,
		'PMEAN':    1,
		'PEEP':     1,
		'△P':       1,
		'FIO2':     2,
		'ETCO2':    2,
		'MVE':      3,
		'MVI':      3,
		'TI':       4,
		'IE':       4,
		'TCE':      4,
		'TPLAT':    4,
		'RR':       4,
		'RRSPON':   4,
		'VTE':      5,
		'VTI':      5,
		'VTKGBW':   5,
		'PIF':      5,
		'PEF':      5,
		'C':        6,
		'R':        6,
		'RSB':      6,
	},
}