module.exports = {
	// 时间选项
	options: [
		{ label: '2小时',  value: 'H2' },
		{ label: '4小时',  value: 'H4' },
		{ label: '8小时',  value: 'H8' },
		{ label: '12小时', value: 'H12' },
		{ label: '1天',    value: 'D1' },
		{ label: '7天',    value: 'D7' },
	],
	// 倍率映射表
	multipleMap: {
		H2:  68,
		H4:  42,
		H8:  21,
		H12: 14,
		D1:  7,
		D7:  1,
	},
	// 单页数据量映射表
	sizeMap: {
		148: 150,
	},
	// code名称映射表
	codeMap: {
		'PEAK':     'MEASURED_DATA_P1_PEAK',
		'PPLAT':    'MEASURED_DATA_P1_PPLAT',
		'PMEAN':    'MEASURED_DATA_P1_PMEAN',
		'PEEP':     'MEASURED_DATA_P1_PEEP',
		'△P':       'MEASURED_DATA_P1_DELTA_P',
		'FIO2':     'MEASURED_DATA_P1_FIO2',
		'ETCO2':    'MEASURED_DATA_P1_ETCO2',
		'MVE':      'MEASURED_DATA_P1_MVE',
		'MVI':      '',
		'TI':       'MEASURED_DATA_P2_TI',
		'IE':       'MEASURED_DATA_P1_IE',
		'TCE':      'MEASURED_DATA_P1_TCE',
		'TPLAT':    'MEASURED_DATA_P1_TPLAT',
		'RR':       'MEASURED_DATA_P1_RR',
		'RRSPONT':  'MEASURED_DATA_P1_RRSPONT',
		'VTE':      'MEASURED_DATA_P2_VTE',
		'VTI':      '',
		'VTKGBW':   'MEASURED_DATA_P1_VTKGBW',
		'PIF':      'MEASURED_DATA_P1_PIF',
		'PEF':      'MEASURED_DATA_P1_PEF',
		'C':        'MEASURED_DATA_P1_C',
		'R':        'MEASURED_DATA_P1_R',
		'RSB':      '',
	},
	keyMap: {
		'PEAK':     'PEAK',
		'PPLAT':    'PPLAT',
		'PMEAN':    'PMEAN',
		'PEEP':     'PEEP',
		'DELTA_P':  '△P',
		'FIO2':     'FIO2',
		'ETCO2':    'ETCO2',
		'MVE':      'MVE',
		'MVI':      'MVI',
		'TI':       'TI',
		'IE':       'IE',
		'TCE':      'TCE',
		'TPLAT':    'TPLAT',
		'RR':       'RR',
		'RRSPONT':  'RRSPONT',
		'VTE':      'VTE',
		'VTI':      'VTI',
		'VTKGBW':   'VTKGBW',
		'PIF':      'PIF',
		'PEF':      'PEF',
		'C':        'C',
		'R':        'R',
		'RSB':      'RSB',
	},
}